export const Baseurl = "https://meta-africa.onrender.com" // Test

export const Endpoint = {
  REGISTER: "auth/register",
  LOGIN: "auth/login",
  ACTIVATE_ACCOUNT: "auth/activate-account",
  GET_USER: "auth/profile/index",
  ADD_TEAM: "basketball/teams/add-team",
  EDIT_TEAM: "basketball/teams/update",
  GET_ALL_TEAM: "basketball/teams/get-all-team",
  GET_TEAM: "basketball/teams/get-team",
  GET_TEAM_BY_ROSTER: "basketball/games/get-games",
  ADD_COACH: "basketball/coach/add-coach",
  EDIT_COACH: "basketball/coach/update",
  ADD_PLAYERS: "basketball/player/add-players",
  EDIT_PLAYERS: "basketball/player/update",
  DELETE_PLAYERS: "basketball/player/delete",
  GET_ALL_PLAYERS: "basketball/player/get-players",
  GET_ALL_COACHES: "basketball/coach/get-coaches",
  DELETE_COACHES: "basketball/coach/delete",
  ADD_LEAGUES: "basketball/league/add-league",
  UPDATE_LEAGUES: "basketball/league/update",
  GET_LEAGUES: "basketball/league/get-all-league",
  GET_ALL_ADMIN: "admin/all-admins",
  CREATE_ADMIN: "admin/create-user",
  EDIT_ADMIN: "admin/create-user",
  ADD_SEASON: "basketball/season/create-season",
  GET_ALL_GAMES: "basketball/games/get-all-games",
  GET_ROSTER_BY_TEAM: "basketball/roster",
  ADD_GAMES: "basketball/games/add-games",
  UPDATE_GAMES: "basketball/games/update-game",
  GAME_SCHEDULE_PER_TEAM: "basketball/games/get-games",
  GET_PLAYER_INFO: "basketball/player/get-player-profile"
}